name: run

on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: clone
        uses: actions/checkout@v4
        
      - name: rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 'stable'

      - name: run
        run: ./run.sh
